#! /usr/bin/env python3

top = '.'
out = 'build'

def options(opt):
  opt.load('clangxx')

def configure(conf):
  conf.load('clangxx')
  conf.check(features='cxx cxxprogram', msg='Check for c++ features')

def build(bld):
  bld.program(
    features='cxx cxxprogram',
    source='main.cpp',
    target='calories',
    cxxflags=['-std=c++17', '-Wall']
  )

